function [x,val,k]=funxBFGS(fun,gfun,G,b,x0)
n=length(x0);
maxk=150;
k=0; epsilon=1e-4;
H0=eye(n);
while(k<maxk)
    % Calculated gradient
    gk=feval(gfun,x0,G,b); 
    %Calculate search direction
    dk=-H0*gk; 
    %Step size generated by precise line search
    ak=-gk'*dk/(dk'*G*dk);
    %Inspection termination criteria
    if(norm(gk)<epsilon), break; end 
    %update
    x0=x0+ak*dk;
    %update x
    dx=ak*dk;
    dy=feval(gfun,x0,G,b)-feval(gfun,x0-dx,G,b);
    %HK formula part
    a1=dx*dy'/(dx'*dy);
    n1=length(a1);
    a2=dy*dx'/(dx'*dy);
    n2=length(a2);
    H0=(eye(n1)-a1)*H0*(eye(n2)-a2)+dx*dx'/(dx'*dy);
    k=k+1;
end
x=x0;
val=feval(fun,x,G,b);
