function [x,val,k]=funxZNND(fun,gfun,Hess,G,b,x0)
maxk=150;
k=0; epsilon=1e-4;
while(k<maxk)
    % Calculated gradient
    gk=feval(gfun,x0,G,b);
    %Calculate Hesse matrix
    Gk=feval(Hess,G); 
    %Solve the equations Gk * dk = - gk and calculate the search direction
    dk=-Gk\gk; 
    %Step size generated by precise line search
    ak=-gk'*dk/(dk'*G*dk);
    %Inspection termination criteria
    if(norm(gk)<epsilon), break; end 
    %to update
    x0=x0+ak*dk;
    k=k+1;
end
x=x0;
val=feval(fun,x,G,b);
