function [x,val,k]=funZNND(fun,gfun,Hess,x0)
maxk=5000;
%Armijo search parameters
rho=0.5;sigma=0.4;
k=0; epsilon=1e-4;
while(k<maxk)
    % Calculated gradient
    g=feval(gfun,x0);
    %Calculate Hesse matrix
    Gk=feval(Hess,x0); 
    %Solve the equations Gk * dk = - gk and calculate the search direction
    d=-Gk\g; 
    %Inspection termination criteria
    if(norm(g)<epsilon), break; end 
     m=0; mk=0;
     %Step size generated by Armijo search
    while(m<20) 
        if(feval(fun,x0+rho^m*d)<feval(fun,x0)+sigma*rho^m*g'*d)
            mk=m; break;
        end
        m=m+1;
    end
    x0=x0+rho^mk*d;
    k=k+1;
end
x=x0;
val=feval(fun,x);
